### ISSUE TITLE
Travis CI?

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-server-roslyn-binaries#5]
Would it be possible for this to push a new version to NPM whenever [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn) has a check-in to master?

**Comment by willl** [comment]
It certainly looks possible. http://docs.travis-ci.com/user/deployment/npm/

**Comment by ctolkien** [comment]
:+1: on this

**Comment by jrieken** [comment]
cool

**Comment by david-driscoll** [comment]
Got this working, but it may have caused #7, I'll follow up tomorrow.
